// Generated by CoffeeScript 1.6.2
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.HandView = (function(_super) {
  __extends(HandView, _super);

  function HandView() {
    _ref = HandView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  HandView.prototype.className = 'hand';

  HandView.prototype.template = _.template('<h2><% if(isDealer){ %>Dealer<% }else{ %>You<% } %> (<span class="score"></span>)</h2>');

  HandView.prototype.events = {
    "click .replay-button": function() {
      return this.model.get('playerHand').replay();
    }
  };

  HandView.prototype.initialize = function() {
    var _this = this;

    this.collection.on('change', function() {
      return _this.render();
    });
    this.collection.on('add', function() {
      return _this.render();
    });
    this.render();
    this.collection.on('win', function() {
      _this.$el.append("<div style=\"font-size:48px; color:green; postion:absolute\">PAY THE MAN!</div>");
      _this.$el.prepend("<div><button class=\"replay-button\">Replay?</button></div>");
      return $('.buttons').hide();
    });
    this.collection.on('tie', function() {
      _this.$el.append("<div style=\"font-size:48px; color:blue; postion:absolute\">PUSH IT!</div>");
      _this.$el.prepend("<div><button class=\"replay-button\">Replay?</button></div>");
      return $('.buttons').hide();
    });
    this.collection.on('lose', function() {
      _this.$el.append("<div style=\"font-size:48px; color:red; postion:absolute\">LOSE MUCH?</div>");
      _this.$el.prepend("<div><button class=\"replay-button\">Replay?</button></div>");
      return $('.buttons').hide();
    });
    this.collection.on('bust', function() {
      _this.$el.append("<div style=\"font-size:48px; color:red; postion:absolute\">HELLA-BUSTED!!!</div>");
      _this.$el.prepend("<div><button class=\"replay-button\">Replay?</button></div>");
      return $('.buttons').hide();
    });
    return this.collection.on('blackjack', function() {
      _this.$el.append("<div style=\"font-size:48px; position:absolute\">BLACK JACK!</div>");
      _this.$el.prepend("<div><button class=\"replay-button\">Replay?</button></div>");
      return $('buttons').hide();
    });
  };

  HandView.prototype.render = function() {
    this.$el.children().detach;
    this.$el.html(this.template(this.collection)).append(this.collection.map(function(card) {
      return new CardView({
        model: card
      }).el;
    }));
    return this.$('.score').text(this.collection.scores()[0]);
  };

  return HandView;

})(Backbone.View);
